### ISSUE TITLE
hi, i successed active server

### ISSUE THREAD

**Issue by Zansword** [greats3an/ggposrv3#2]
but looks like this server require client. after i active this, what should we have to do?

**Comment by mos9527** [comment]
Just like Fightcade, you do need a emulator backend to play online. 
- `ggposrv3` uses its own [moscade-fbneo](https://github.com/mos9527/moscade-fbneo/releases). Get the latest release from [this link](https://github.com/mos9527/moscade-fbneo/releases/download/release/release.zip).
- Once downloaded & extracted, you'll need to run the main executable (i.e. `moscadefbneo.exe`) at least once for it to register the `moscade://` URI scheme. It is used by the web front end to launch games & for the emulator to connect to the server.
- Game ROMs needs to be put into the `roms/` folder before playing. After which you may test your setup with `PLAY LOCALLY` option in any game channel. Games should be automatically loaded and playable as if you loaded them manually.

The setup is the same for the peer player.

Once entered a channel, you can "challenge" other free players by clicking on their IDs. Once the peer accepted, click on "JOIN MATCH" to start the match.

*A few more words*
- The emulator backend isn't localized so it's all in Chinese, Google translate may help somewhat. 
- This project is still a WIP so expect some quirks and bugs I have yet to fix. Continue in this thread if you encountered any more issues.

 Thank you for testing!
